//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class error_log
    {
        public int Error_ID { get; set; }
        public string Error_Message { get; set; }
        public string Error_Inner { get; set; }
        public string STATUS { get; set; }
        public System.DateTime UPDATEDDATETIME { get; set; }
    }
}
