//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_organization
    {
        public int ID_ORGANIZATION { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_EMAIL { get; set; }
        public string DESCRIPTION { get; set; }
        public string COMPANY_NO { get; set; }
        public string CORPARATE_ID { get; set; }
        public string GSTIN { get; set; }
        public Nullable<int> ID_INDUSTRY { get; set; }
        public Nullable<int> ID_INDUSTRY_TYPE { get; set; }
        public string LOGO { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE_TIME { get; set; }
        public string INDUSTRY_TYPE { get; set; }
        public string TELEPHONE { get; set; }
        public string PAYMENT_CODE { get; set; }
        public Nullable<int> annual_revenue_id { get; set; }
        public string website_url { get; set; }
        public string Company_Address { get; set; }
        public string founder { get; set; }
        public string sector { get; set; }
        public string social_media_links { get; set; }
        public Nullable<System.DateTime> founded_date { get; set; }
        public string comp_description { get; set; }
        public string company_HO { get; set; }
        public Nullable<int> employee_strength_id { get; set; }
        public string save_type { get; set; }
        public string Company_Address2 { get; set; }
        public string code { get; set; }
        public string state { get; set; }
        public string cityname { get; set; }
        public string pincode { get; set; }
    }
}
