//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_cms_users
    {
        public int ID_USER { get; set; }
        public int ID_ROLE { get; set; }
        public int ID_ORGANIZATION { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE_TIME { get; set; }
        public Nullable<int> cmd_user_type { get; set; }
        public string employee_id { get; set; }
        public string employee_name { get; set; }
        public string profileimage { get; set; }
        public string Name { get; set; }
        public string professional_email { get; set; }
        public string alternate_email { get; set; }
        public string designation { get; set; }
        public string social_media_links { get; set; }
        public string Contact_number { get; set; }
        public string office_address { get; set; }
        public string save_type { get; set; }
    }
}
