//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_m2ostEntities : DbContext
    {
        public db_m2ostEntities()
            : base("name=db_m2ostEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<downtime_log> downtime_log { get; set; }
        public virtual DbSet<error_log> error_log { get; set; }
        public virtual DbSet<job_cms_users> job_cms_users { get; set; }
        public virtual DbSet<job_organization> job_organization { get; set; }
        public virtual DbSet<masti_teacher_galleryfolder> masti_teacher_galleryfolder { get; set; }
        public virtual DbSet<masti_teacher_photo_mapping> masti_teacher_photo_mapping { get; set; }
        public virtual DbSet<sc_game_element_weightage> sc_game_element_weightage { get; set; }
        public virtual DbSet<sc_program_assessment_scoring> sc_program_assessment_scoring { get; set; }
        public virtual DbSet<sc_program_content_summary> sc_program_content_summary { get; set; }
        public virtual DbSet<sc_program_kpi_score> sc_program_kpi_score { get; set; }
        public virtual DbSet<sc_program_kpi_weightage> sc_program_kpi_weightage { get; set; }
        public virtual DbSet<sc_program_log> sc_program_log { get; set; }
        public virtual DbSet<sc_report_game_process_path> sc_report_game_process_path { get; set; }
        public virtual DbSet<sc_report_game_process_score> sc_report_game_process_score { get; set; }
        public virtual DbSet<special_metric_master> special_metric_master { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<tbl_academic_tile_log> tbl_academic_tile_log { get; set; }
        public virtual DbSet<tbl_academic_tiles> tbl_academic_tiles { get; set; }
        public virtual DbSet<tbl_academy_brief_log> tbl_academy_brief_log { get; set; }
        public virtual DbSet<tbl_academy_level_brief_restriction> tbl_academy_level_brief_restriction { get; set; }
        public virtual DbSet<tbl_action> tbl_action { get; set; }
        public virtual DbSet<tbl_annual_revenue_master> tbl_annual_revenue_master { get; set; }
        public virtual DbSet<tbl_api_authenticate> tbl_api_authenticate { get; set; }
        public virtual DbSet<tbl_assessment> tbl_assessment { get; set; }
        public virtual DbSet<tbl_assessment_answer> tbl_assessment_answer { get; set; }
        public virtual DbSet<tbl_assessment_audit> tbl_assessment_audit { get; set; }
        public virtual DbSet<tbl_assessment_categoty_mapping> tbl_assessment_categoty_mapping { get; set; }
        public virtual DbSet<tbl_assessment_general> tbl_assessment_general { get; set; }
        public virtual DbSet<tbl_assessment_header> tbl_assessment_header { get; set; }
        public virtual DbSet<tbl_assessment_index> tbl_assessment_index { get; set; }
        public virtual DbSet<tbl_assessment_mapping> tbl_assessment_mapping { get; set; }
        public virtual DbSet<tbl_assessment_push> tbl_assessment_push { get; set; }
        public virtual DbSet<tbl_assessment_question> tbl_assessment_question { get; set; }
        public virtual DbSet<tbl_assessment_scoring_key> tbl_assessment_scoring_key { get; set; }
        public virtual DbSet<tbl_assessment_sheet> tbl_assessment_sheet { get; set; }
        public virtual DbSet<tbl_assessment_theme> tbl_assessment_theme { get; set; }
        public virtual DbSet<tbl_assessment_user_assignment> tbl_assessment_user_assignment { get; set; }
        public virtual DbSet<tbl_assessmnt_log> tbl_assessmnt_log { get; set; }
        public virtual DbSet<tbl_assignment_role_assessment> tbl_assignment_role_assessment { get; set; }
        public virtual DbSet<tbl_assignment_role_content> tbl_assignment_role_content { get; set; }
        public virtual DbSet<tbl_assignment_role_program> tbl_assignment_role_program { get; set; }
        public virtual DbSet<tbl_authcode> tbl_authcode { get; set; }
        public virtual DbSet<tbl_badge_data> tbl_badge_data { get; set; }
        public virtual DbSet<tbl_badge_master> tbl_badge_master { get; set; }
        public virtual DbSet<tbl_badge_reward_mapping> tbl_badge_reward_mapping { get; set; }
        public virtual DbSet<tbl_badge_won_message> tbl_badge_won_message { get; set; }
        public virtual DbSet<tbl_banner> tbl_banner { get; set; }
        public virtual DbSet<tbl_banner_ad_config> tbl_banner_ad_config { get; set; }
        public virtual DbSet<tbl_banner_body> tbl_banner_body { get; set; }
        public virtual DbSet<tbl_banner_config_master> tbl_banner_config_master { get; set; }
        public virtual DbSet<tbl_batch> tbl_batch { get; set; }
        public virtual DbSet<tbl_brief_answer> tbl_brief_answer { get; set; }
        public virtual DbSet<tbl_brief_audit> tbl_brief_audit { get; set; }
        public virtual DbSet<tbl_brief_b2c_index> tbl_brief_b2c_index { get; set; }
        public virtual DbSet<tbl_brief_b2c_right_audit> tbl_brief_b2c_right_audit { get; set; }
        public virtual DbSet<tbl_brief_b2c_score_audit> tbl_brief_b2c_score_audit { get; set; }
        public virtual DbSet<tbl_brief_category> tbl_brief_category { get; set; }
        public virtual DbSet<tbl_brief_category_mapping> tbl_brief_category_mapping { get; set; }
        public virtual DbSet<tbl_brief_category_tile> tbl_brief_category_tile { get; set; }
        public virtual DbSet<tbl_brief_enquiry> tbl_brief_enquiry { get; set; }
        public virtual DbSet<tbl_brief_feedback_media> tbl_brief_feedback_media { get; set; }
        public virtual DbSet<tbl_brief_index> tbl_brief_index { get; set; }
        public virtual DbSet<tbl_brief_log> tbl_brief_log { get; set; }
        public virtual DbSet<tbl_brief_log_audit> tbl_brief_log_audit { get; set; }
        public virtual DbSet<tbl_brief_m2ost_category_mapping> tbl_brief_m2ost_category_mapping { get; set; }
        public virtual DbSet<tbl_brief_master> tbl_brief_master { get; set; }
        public virtual DbSet<tbl_brief_master_body> tbl_brief_master_body { get; set; }
        public virtual DbSet<tbl_brief_master_template> tbl_brief_master_template { get; set; }
        public virtual DbSet<tbl_brief_metadata> tbl_brief_metadata { get; set; }
        public virtual DbSet<tbl_brief_progdist_mapping> tbl_brief_progdist_mapping { get; set; }
        public virtual DbSet<tbl_brief_question> tbl_brief_question { get; set; }
        public virtual DbSet<tbl_brief_question_complexity> tbl_brief_question_complexity { get; set; }
        public virtual DbSet<tbl_brief_question_mapping> tbl_brief_question_mapping { get; set; }
        public virtual DbSet<tbl_brief_question_metadata> tbl_brief_question_metadata { get; set; }
        public virtual DbSet<tbl_brief_read_status> tbl_brief_read_status { get; set; }
        public virtual DbSet<tbl_brief_status> tbl_brief_status { get; set; }
        public virtual DbSet<tbl_brief_subcategory> tbl_brief_subcategory { get; set; }
        public virtual DbSet<tbl_brief_tile_academic_mapping> tbl_brief_tile_academic_mapping { get; set; }
        public virtual DbSet<tbl_brief_tile_category_mapping> tbl_brief_tile_category_mapping { get; set; }
        public virtual DbSet<tbl_brief_tile_level_brief_restriction> tbl_brief_tile_level_brief_restriction { get; set; }
        public virtual DbSet<tbl_brief_user_assignment> tbl_brief_user_assignment { get; set; }
        public virtual DbSet<tbl_brief_user_feedback_master> tbl_brief_user_feedback_master { get; set; }
        public virtual DbSet<tbl_brief_version_control> tbl_brief_version_control { get; set; }
        public virtual DbSet<tbl_buisiness_stages_master> tbl_buisiness_stages_master { get; set; }
        public virtual DbSet<tbl_business_type> tbl_business_type { get; set; }
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_category_associantion> tbl_category_associantion { get; set; }
        public virtual DbSet<tbl_category_default> tbl_category_default { get; set; }
        public virtual DbSet<tbl_category_heading> tbl_category_heading { get; set; }
        public virtual DbSet<tbl_category_heading_default> tbl_category_heading_default { get; set; }
        public virtual DbSet<tbl_category_order> tbl_category_order { get; set; }
        public virtual DbSet<tbl_category_tiles> tbl_category_tiles { get; set; }
        public virtual DbSet<tbl_category_tiles_default> tbl_category_tiles_default { get; set; }
        public virtual DbSet<tbl_ce_career_evaluation_master> tbl_ce_career_evaluation_master { get; set; }
        public virtual DbSet<tbl_ce_category_mapping> tbl_ce_category_mapping { get; set; }
        public virtual DbSet<tbl_ce_company_details> tbl_ce_company_details { get; set; }
        public virtual DbSet<tbl_ce_evaluation_audit> tbl_ce_evaluation_audit { get; set; }
        public virtual DbSet<tbl_ce_evaluation_completion_report> tbl_ce_evaluation_completion_report { get; set; }
        public virtual DbSet<tbl_ce_evaluation_index> tbl_ce_evaluation_index { get; set; }
        public virtual DbSet<tbl_ce_evaluation_job_organization_setup> tbl_ce_evaluation_job_organization_setup { get; set; }
        public virtual DbSet<tbl_ce_evaluation_jobindustry> tbl_ce_evaluation_jobindustry { get; set; }
        public virtual DbSet<tbl_ce_evaluation_jobindustry_tgc_setup> tbl_ce_evaluation_jobindustry_tgc_setup { get; set; }
        public virtual DbSet<tbl_ce_evaluation_jobindustry_user_mapping> tbl_ce_evaluation_jobindustry_user_mapping { get; set; }
        public virtual DbSet<tbl_ce_evaluation_jobrole> tbl_ce_evaluation_jobrole { get; set; }
        public virtual DbSet<tbl_ce_evaluation_jobrole_user_mapping> tbl_ce_evaluation_jobrole_user_mapping { get; set; }
        public virtual DbSet<tbl_ce_evaluation_log> tbl_ce_evaluation_log { get; set; }
        public virtual DbSet<tbl_ce_evaluation_progdist_mapping> tbl_ce_evaluation_progdist_mapping { get; set; }
        public virtual DbSet<tbl_ce_evaluation_role_answerkey_setup> tbl_ce_evaluation_role_answerkey_setup { get; set; }
        public virtual DbSet<tbl_ce_evaluation_tile> tbl_ce_evaluation_tile { get; set; }
        public virtual DbSet<tbl_ce_evalution_answer_key> tbl_ce_evalution_answer_key { get; set; }
        public virtual DbSet<tbl_ce_evalution_answer_key_setup> tbl_ce_evalution_answer_key_setup { get; set; }
        public virtual DbSet<tbl_ce_evalution_psychometric_setup> tbl_ce_evalution_psychometric_setup { get; set; }
        public virtual DbSet<tbl_ce_industry> tbl_ce_industry { get; set; }
        public virtual DbSet<tbl_ce_industry_role> tbl_ce_industry_role { get; set; }
        public virtual DbSet<tbl_ce_organization_ce_setup> tbl_ce_organization_ce_setup { get; set; }
        public virtual DbSet<tbl_ce_organization_ce_setup_industry> tbl_ce_organization_ce_setup_industry { get; set; }
        public virtual DbSet<tbl_certificate_assignment> tbl_certificate_assignment { get; set; }
        public virtual DbSet<tbl_certificate_configure> tbl_certificate_configure { get; set; }
        public virtual DbSet<tbl_certificate_configure_data> tbl_certificate_configure_data { get; set; }
        public virtual DbSet<tbl_childinformation> tbl_childinformation { get; set; }
        public virtual DbSet<tbl_cms_role_action> tbl_cms_role_action { get; set; }
        public virtual DbSet<tbl_cms_role_action_mapping> tbl_cms_role_action_mapping { get; set; }
        public virtual DbSet<tbl_cms_roles> tbl_cms_roles { get; set; }
        public virtual DbSet<tbl_cms_users> tbl_cms_users { get; set; }
        public virtual DbSet<tbl_college_list> tbl_college_list { get; set; }
        public virtual DbSet<tbl_color_config> tbl_color_config { get; set; }
        public virtual DbSet<tbl_color_config_flag> tbl_color_config_flag { get; set; }
        public virtual DbSet<tbl_content> tbl_content { get; set; }
        public virtual DbSet<tbl_content_answer> tbl_content_answer { get; set; }
        public virtual DbSet<tbl_content_answer_default> tbl_content_answer_default { get; set; }
        public virtual DbSet<tbl_content_answer_steps> tbl_content_answer_steps { get; set; }
        public virtual DbSet<tbl_content_banner> tbl_content_banner { get; set; }
        public virtual DbSet<tbl_content_counters> tbl_content_counters { get; set; }
        public virtual DbSet<tbl_content_default> tbl_content_default { get; set; }
        public virtual DbSet<tbl_content_footer> tbl_content_footer { get; set; }
        public virtual DbSet<tbl_content_header> tbl_content_header { get; set; }
        public virtual DbSet<tbl_content_header_footer> tbl_content_header_footer { get; set; }
        public virtual DbSet<tbl_content_level> tbl_content_level { get; set; }
        public virtual DbSet<tbl_content_link> tbl_content_link { get; set; }
        public virtual DbSet<tbl_content_metadata> tbl_content_metadata { get; set; }
        public virtual DbSet<tbl_content_notification_master> tbl_content_notification_master { get; set; }
        public virtual DbSet<tbl_content_organization_mapping> tbl_content_organization_mapping { get; set; }
        public virtual DbSet<tbl_content_organization_mapping_default> tbl_content_organization_mapping_default { get; set; }
        public virtual DbSet<tbl_content_program_mapping> tbl_content_program_mapping { get; set; }
        public virtual DbSet<tbl_content_right_association> tbl_content_right_association { get; set; }
        public virtual DbSet<tbl_content_role_mapping> tbl_content_role_mapping { get; set; }
        public virtual DbSet<tbl_content_type> tbl_content_type { get; set; }
        public virtual DbSet<tbl_content_type_link> tbl_content_type_link { get; set; }
        public virtual DbSet<tbl_content_user_assisgnment> tbl_content_user_assisgnment { get; set; }
        public virtual DbSet<tbl_couponsredeemed> tbl_couponsredeemed { get; set; }
        public virtual DbSet<tbl_csst_role> tbl_csst_role { get; set; }
        public virtual DbSet<tbl_currency_data> tbl_currency_data { get; set; }
        public virtual DbSet<tbl_currency_points> tbl_currency_points { get; set; }
        public virtual DbSet<tbl_cv_additional_info> tbl_cv_additional_info { get; set; }
        public virtual DbSet<tbl_cv_education> tbl_cv_education { get; set; }
        public virtual DbSet<tbl_cv_master> tbl_cv_master { get; set; }
        public virtual DbSet<tbl_cv_personel_info> tbl_cv_personel_info { get; set; }
        public virtual DbSet<tbl_cv_project> tbl_cv_project { get; set; }
        public virtual DbSet<tbl_degree_master> tbl_degree_master { get; set; }
        public virtual DbSet<tbl_device_type> tbl_device_type { get; set; }
        public virtual DbSet<tbl_email_feedback_user> tbl_email_feedback_user { get; set; }
        public virtual DbSet<tbl_email_template> tbl_email_template { get; set; }
        public virtual DbSet<tbl_email_template_body> tbl_email_template_body { get; set; }
        public virtual DbSet<tbl_employee_strength_master> tbl_employee_strength_master { get; set; }
        public virtual DbSet<tbl_enquiry_reason> tbl_enquiry_reason { get; set; }
        public virtual DbSet<tbl_entrepreneurship_files> tbl_entrepreneurship_files { get; set; }
        public virtual DbSet<tbl_entrepreneurship_master> tbl_entrepreneurship_master { get; set; }
        public virtual DbSet<tbl_event_organisation_master> tbl_event_organisation_master { get; set; }
        public virtual DbSet<tbl_event_sponsor_master> tbl_event_sponsor_master { get; set; }
        public virtual DbSet<tbl_event_type_mapping> tbl_event_type_mapping { get; set; }
        public virtual DbSet<tbl_event_type_master> tbl_event_type_master { get; set; }
        public virtual DbSet<tbl_excel> tbl_excel { get; set; }
        public virtual DbSet<tbl_facilitator_users> tbl_facilitator_users { get; set; }
        public virtual DbSet<tbl_feedback_bank> tbl_feedback_bank { get; set; }
        public virtual DbSet<tbl_feedback_bank_link> tbl_feedback_bank_link { get; set; }
        public virtual DbSet<tbl_feedback_data> tbl_feedback_data { get; set; }
        public virtual DbSet<tbl_feedback_master> tbl_feedback_master { get; set; }
        public virtual DbSet<tbl_feedback_media> tbl_feedback_media { get; set; }
        public virtual DbSet<tbl_feedback_role> tbl_feedback_role { get; set; }
        public virtual DbSet<tbl_foundation_master> tbl_foundation_master { get; set; }
        public virtual DbSet<tbl_game_academic_mapping> tbl_game_academic_mapping { get; set; }
        public virtual DbSet<tbl_game_creation> tbl_game_creation { get; set; }
        public virtual DbSet<tbl_game_group> tbl_game_group { get; set; }
        public virtual DbSet<tbl_game_group_association> tbl_game_group_association { get; set; }
        public virtual DbSet<tbl_game_group_participatant> tbl_game_group_participatant { get; set; }
        public virtual DbSet<tbl_game_master> tbl_game_master { get; set; }
        public virtual DbSet<tbl_game_metric_kpi_mapping> tbl_game_metric_kpi_mapping { get; set; }
        public virtual DbSet<tbl_game_path> tbl_game_path { get; set; }
        public virtual DbSet<tbl_game_phase> tbl_game_phase { get; set; }
        public virtual DbSet<tbl_game_process_path> tbl_game_process_path { get; set; }
        public virtual DbSet<tbl_game_solo> tbl_game_solo { get; set; }
        public virtual DbSet<tbl_game_user_data> tbl_game_user_data { get; set; }
        public virtual DbSet<tbl_graduation_year> tbl_graduation_year { get; set; }
        public virtual DbSet<tbl_industry> tbl_industry { get; set; }
        public virtual DbSet<tbl_job> tbl_job { get; set; }
        public virtual DbSet<tbl_job_assessment_mapping> tbl_job_assessment_mapping { get; set; }
        public virtual DbSet<tbl_job_category> tbl_job_category { get; set; }
        public virtual DbSet<tbl_job_category_header> tbl_job_category_header { get; set; }
        public virtual DbSet<tbl_job_email_template_body> tbl_job_email_template_body { get; set; }
        public virtual DbSet<tbl_job_interview_master> tbl_job_interview_master { get; set; }
        public virtual DbSet<tbl_job_interview_result_log> tbl_job_interview_result_log { get; set; }
        public virtual DbSet<tbl_job_interview_rounds_mapping> tbl_job_interview_rounds_mapping { get; set; }
        public virtual DbSet<tbl_job_location_mapping> tbl_job_location_mapping { get; set; }
        public virtual DbSet<tbl_job_offline_mapping> tbl_job_offline_mapping { get; set; }
        public virtual DbSet<tbl_job_online_mapping> tbl_job_online_mapping { get; set; }
        public virtual DbSet<tbl_job_publish_calender_report> tbl_job_publish_calender_report { get; set; }
        public virtual DbSet<tbl_job_reject_feedback_log> tbl_job_reject_feedback_log { get; set; }
        public virtual DbSet<tbl_job_round_histroy> tbl_job_round_histroy { get; set; }
        public virtual DbSet<tbl_job_telephonic_mapping> tbl_job_telephonic_mapping { get; set; }
        public virtual DbSet<tbl_job_user_log> tbl_job_user_log { get; set; }
        public virtual DbSet<tbl_job_zoom_meeting_id> tbl_job_zoom_meeting_id { get; set; }
        public virtual DbSet<tbl_joburl_master> tbl_joburl_master { get; set; }
        public virtual DbSet<tbl_kpi_grid> tbl_kpi_grid { get; set; }
        public virtual DbSet<tbl_kpi_master> tbl_kpi_master { get; set; }
        public virtual DbSet<tbl_kpi_program_scoring> tbl_kpi_program_scoring { get; set; }
        public virtual DbSet<tbl_landing_page> tbl_landing_page { get; set; }
        public virtual DbSet<tbl_league_message> tbl_league_message { get; set; }
        public virtual DbSet<tbl_leagues_data> tbl_leagues_data { get; set; }
        public virtual DbSet<tbl_mail_verification> tbl_mail_verification { get; set; }
        public virtual DbSet<tbl_menu> tbl_menu { get; set; }
        public virtual DbSet<tbl_menu_default> tbl_menu_default { get; set; }
        public virtual DbSet<tbl_menu_type> tbl_menu_type { get; set; }
        public virtual DbSet<tbl_min_qualification_mapping> tbl_min_qualification_mapping { get; set; }
        public virtual DbSet<tbl_mini_quali_master> tbl_mini_quali_master { get; set; }
        public virtual DbSet<tbl_mutthi_mein_sitare_milestone> tbl_mutthi_mein_sitare_milestone { get; set; }
        public virtual DbSet<tbl_mutthi_mein_sitare_skill> tbl_mutthi_mein_sitare_skill { get; set; }
        public virtual DbSet<tbl_mutthi_skill_development_detail> tbl_mutthi_skill_development_detail { get; set; }
        public virtual DbSet<tbl_mutthi_skill_milestone_detail> tbl_mutthi_skill_milestone_detail { get; set; }
        public virtual DbSet<tbl_mutthimeinsitare_master> tbl_mutthimeinsitare_master { get; set; }
        public virtual DbSet<tbl_news_ticker> tbl_news_ticker { get; set; }
        public virtual DbSet<tbl_non_disclousure_clause_content> tbl_non_disclousure_clause_content { get; set; }
        public virtual DbSet<tbl_non_disclousure_clause_log> tbl_non_disclousure_clause_log { get; set; }
        public virtual DbSet<tbl_notification> tbl_notification { get; set; }
        public virtual DbSet<tbl_notification_config> tbl_notification_config { get; set; }
        public virtual DbSet<tbl_notification_pre_config> tbl_notification_pre_config { get; set; }
        public virtual DbSet<tbl_notification_reminder> tbl_notification_reminder { get; set; }
        public virtual DbSet<tbl_offline_expiry> tbl_offline_expiry { get; set; }
        public virtual DbSet<tbl_org_mapping> tbl_org_mapping { get; set; }
        public virtual DbSet<tbl_organisation_banner> tbl_organisation_banner { get; set; }
        public virtual DbSet<tbl_organisation_banner_links> tbl_organisation_banner_links { get; set; }
        public virtual DbSet<tbl_organisation_status> tbl_organisation_status { get; set; }
        public virtual DbSet<tbl_organization> tbl_organization { get; set; }
        public virtual DbSet<tbl_popup_info> tbl_popup_info { get; set; }
        public virtual DbSet<tbl_popup_info_mapping> tbl_popup_info_mapping { get; set; }
        public virtual DbSet<tbl_profile> tbl_profile { get; set; }
        public virtual DbSet<tbl_promocode_master> tbl_promocode_master { get; set; }
        public virtual DbSet<tbl_referral_code_master> tbl_referral_code_master { get; set; }
        public virtual DbSet<tbl_referral_code_points_config> tbl_referral_code_points_config { get; set; }
        public virtual DbSet<tbl_referral_code_user_mapping> tbl_referral_code_user_mapping { get; set; }
        public virtual DbSet<tbl_relegtion_data> tbl_relegtion_data { get; set; }
        public virtual DbSet<tbl_reminder_notification_config> tbl_reminder_notification_config { get; set; }
        public virtual DbSet<tbl_reminder_notification_log> tbl_reminder_notification_log { get; set; }
        public virtual DbSet<tbl_report_content> tbl_report_content { get; set; }
        public virtual DbSet<tbl_report_login_log> tbl_report_login_log { get; set; }
        public virtual DbSet<tbl_restriction_user_log> tbl_restriction_user_log { get; set; }
        public virtual DbSet<tbl_rewards_master> tbl_rewards_master { get; set; }
        public virtual DbSet<tbl_rewards_redeem_master> tbl_rewards_redeem_master { get; set; }
        public virtual DbSet<tbl_role> tbl_role { get; set; }
        public virtual DbSet<tbl_role_user_mapping> tbl_role_user_mapping { get; set; }
        public virtual DbSet<tbl_rs_type_qna> tbl_rs_type_qna { get; set; }
        public virtual DbSet<tbl_saksham_assessment_detail> tbl_saksham_assessment_detail { get; set; }
        public virtual DbSet<tbl_saksham_assessment_master> tbl_saksham_assessment_master { get; set; }
        public virtual DbSet<tbl_saksham_assessment_milestone_detail> tbl_saksham_assessment_milestone_detail { get; set; }
        public virtual DbSet<tbl_saksham_assessment_skill_detail> tbl_saksham_assessment_skill_detail { get; set; }
        public virtual DbSet<tbl_scheduled_event> tbl_scheduled_event { get; set; }
        public virtual DbSet<tbl_scheduled_event_subscription_log> tbl_scheduled_event_subscription_log { get; set; }
        public virtual DbSet<tbl_signup_config> tbl_signup_config { get; set; }
        public virtual DbSet<tbl_skill_development> tbl_skill_development { get; set; }
        public virtual DbSet<tbl_skill_milestone> tbl_skill_milestone { get; set; }
        public virtual DbSet<tbl_social_entrepreneurship> tbl_social_entrepreneurship { get; set; }
        public virtual DbSet<tbl_social_entrepreneurship_product_mapping> tbl_social_entrepreneurship_product_mapping { get; set; }
        public virtual DbSet<tbl_social_entrepreneurship_product_master> tbl_social_entrepreneurship_product_master { get; set; }
        public virtual DbSet<tbl_social_platform_active_directory> tbl_social_platform_active_directory { get; set; }
        public virtual DbSet<tbl_social_platform_master> tbl_social_platform_master { get; set; }
        public virtual DbSet<tbl_special_metric_master> tbl_special_metric_master { get; set; }
        public virtual DbSet<tbl_sso_log> tbl_sso_log { get; set; }
        public virtual DbSet<tbl_stream_master> tbl_stream_master { get; set; }
        public virtual DbSet<tbl_sub_event_type_mapping> tbl_sub_event_type_mapping { get; set; }
        public virtual DbSet<tbl_sub_event_type_master> tbl_sub_event_type_master { get; set; }
        public virtual DbSet<tbl_subscriber_attendance> tbl_subscriber_attendance { get; set; }
        public virtual DbSet<tbl_subscriptions> tbl_subscriptions { get; set; }
        public virtual DbSet<tbl_sul_event_college_list> tbl_sul_event_college_list { get; set; }
        public virtual DbSet<tbl_sul_fest_event_mapping> tbl_sul_fest_event_mapping { get; set; }
        public virtual DbSet<tbl_sul_fest_event_registration> tbl_sul_fest_event_registration { get; set; }
        public virtual DbSet<tbl_sul_fest_master> tbl_sul_fest_master { get; set; }
        public virtual DbSet<tbl_sul_fest_otp> tbl_sul_fest_otp { get; set; }
        public virtual DbSet<tbl_sul_fest_otp_expiry_config> tbl_sul_fest_otp_expiry_config { get; set; }
        public virtual DbSet<tbl_sul_higher_education_master> tbl_sul_higher_education_master { get; set; }
        public virtual DbSet<tbl_sul_higher_education_timeslot> tbl_sul_higher_education_timeslot { get; set; }
        public virtual DbSet<tbl_sul_higher_education_user_registration> tbl_sul_higher_education_user_registration { get; set; }
        public virtual DbSet<tbl_sul_seminar_master> tbl_sul_seminar_master { get; set; }
        public virtual DbSet<tbl_sul_seminar_timeslot> tbl_sul_seminar_timeslot { get; set; }
        public virtual DbSet<tbl_sul_seminar_timeslot_new> tbl_sul_seminar_timeslot_new { get; set; }
        public virtual DbSet<tbl_sul_seminar_user_registration> tbl_sul_seminar_user_registration { get; set; }
        public virtual DbSet<tbl_sul_slot_seminar> tbl_sul_slot_seminar { get; set; }
        public virtual DbSet<tbl_survey> tbl_survey { get; set; }
        public virtual DbSet<tbl_survey_bank> tbl_survey_bank { get; set; }
        public virtual DbSet<tbl_survey_bank_link> tbl_survey_bank_link { get; set; }
        public virtual DbSet<tbl_survey_data> tbl_survey_data { get; set; }
        public virtual DbSet<tbl_task> tbl_task { get; set; }
        public virtual DbSet<tbl_temp_user_upload> tbl_temp_user_upload { get; set; }
        public virtual DbSet<tbl_theme_leagues> tbl_theme_leagues { get; set; }
        public virtual DbSet<tbl_theme_master> tbl_theme_master { get; set; }
        public virtual DbSet<tbl_theme_metric> tbl_theme_metric { get; set; }
        public virtual DbSet<tbl_theme_organisation_mapping> tbl_theme_organisation_mapping { get; set; }
        public virtual DbSet<tbl_themes> tbl_themes { get; set; }
        public virtual DbSet<tbl_third_party_app_right_swipe_mapping> tbl_third_party_app_right_swipe_mapping { get; set; }
        public virtual DbSet<tbl_third_party_right_swipe_m2ost> tbl_third_party_right_swipe_m2ost { get; set; }
        public virtual DbSet<tbl_university_kpi_grid> tbl_university_kpi_grid { get; set; }
        public virtual DbSet<tbl_university_kpi_master> tbl_university_kpi_master { get; set; }
        public virtual DbSet<tbl_university_special_point_grid> tbl_university_special_point_grid { get; set; }
        public virtual DbSet<tbl_university_special_points_master> tbl_university_special_points_master { get; set; }
        public virtual DbSet<tbl_url_notification_master> tbl_url_notification_master { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tbl_user_applied_job> tbl_user_applied_job { get; set; }
        public virtual DbSet<tbl_user_badge_log> tbl_user_badge_log { get; set; }
        public virtual DbSet<tbl_user_currency_log> tbl_user_currency_log { get; set; }
        public virtual DbSet<tbl_user_data> tbl_user_data { get; set; }
        public virtual DbSet<tbl_user_device_link> tbl_user_device_link { get; set; }
        public virtual DbSet<tbl_user_enquiry_data> tbl_user_enquiry_data { get; set; }
        public virtual DbSet<tbl_user_event_mapping> tbl_user_event_mapping { get; set; }
        public virtual DbSet<tbl_user_extra_curricular_certificates> tbl_user_extra_curricular_certificates { get; set; }
        public virtual DbSet<tbl_user_game_assignment> tbl_user_game_assignment { get; set; }
        public virtual DbSet<tbl_user_game_score_log> tbl_user_game_score_log { get; set; }
        public virtual DbSet<tbl_user_game_special_metric_score_log> tbl_user_game_special_metric_score_log { get; set; }
        public virtual DbSet<tbl_user_gcm_log> tbl_user_gcm_log { get; set; }
        public virtual DbSet<tbl_user_job_preferences> tbl_user_job_preferences { get; set; }
        public virtual DbSet<tbl_user_job_preferences_category> tbl_user_job_preferences_category { get; set; }
        public virtual DbSet<tbl_user_job_preferences_job_type> tbl_user_job_preferences_job_type { get; set; }
        public virtual DbSet<tbl_user_job_preferences_location> tbl_user_job_preferences_location { get; set; }
        public virtual DbSet<tbl_user_job_preferences_skill> tbl_user_job_preferences_skill { get; set; }
        public virtual DbSet<tbl_user_league_log> tbl_user_league_log { get; set; }
        public virtual DbSet<tbl_user_log_master> tbl_user_log_master { get; set; }
        public virtual DbSet<tbl_user_login_log> tbl_user_login_log { get; set; }
        public virtual DbSet<tbl_user_programs> tbl_user_programs { get; set; }
        public virtual DbSet<tbl_user_ref_mapping> tbl_user_ref_mapping { get; set; }
        public virtual DbSet<tbl_user_zone> tbl_user_zone { get; set; }
        public virtual DbSet<tbl_user_zone_master> tbl_user_zone_master { get; set; }
        public virtual DbSet<tbl_version_control> tbl_version_control { get; set; }
        public virtual DbSet<tbl_version_control_ios> tbl_version_control_ios { get; set; }
        public virtual DbSet<tbl_video_cv> tbl_video_cv { get; set; }
        public virtual DbSet<tbl_web_version_control> tbl_web_version_control { get; set; }
        public virtual DbSet<tbl_welcome_gif> tbl_welcome_gif { get; set; }
        public virtual DbSet<userscore> userscores { get; set; }
    
        public virtual int delete_user(string emailid, Nullable<int> orgid)
        {
            var emailidParameter = emailid != null ?
                new ObjectParameter("emailid", emailid) :
                new ObjectParameter("emailid", typeof(string));
    
            var orgidParameter = orgid.HasValue ?
                new ObjectParameter("orgid", orgid) :
                new ObjectParameter("orgid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_user", emailidParameter, orgidParameter);
        }
    
        public virtual ObjectResult<getOrgDashboard_Result> getOrgDashboard()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getOrgDashboard_Result>("getOrgDashboard");
        }
    
        public virtual ObjectResult<getPopupInfo_Result> getPopupInfo(Nullable<int> popupinfo, Nullable<int> oRGID)
        {
            var popupinfoParameter = popupinfo.HasValue ?
                new ObjectParameter("popupinfo", popupinfo) :
                new ObjectParameter("popupinfo", typeof(int));
    
            var oRGIDParameter = oRGID.HasValue ?
                new ObjectParameter("ORGID", oRGID) :
                new ObjectParameter("ORGID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPopupInfo_Result>("getPopupInfo", popupinfoParameter, oRGIDParameter);
        }
    }
}
