//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class masti_teacher_galleryfolder
    {
        public int id_gallery_folder { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public string folder_name { get; set; }
        public Nullable<double> folder_size { get; set; }
        public Nullable<System.DateTime> updated_time { get; set; }
        public Nullable<int> id_org { get; set; }
    }
}
