//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class sc_report_game_process_path
    {
        public int id_sc_report_game_process_path { get; set; }
        public Nullable<int> id_game { get; set; }
        public Nullable<int> id_organization { get; set; }
        public Nullable<int> process_type { get; set; }
        public Nullable<int> sequence_number { get; set; }
        public Nullable<double> score { get; set; }
        public Nullable<double> element_weightage { get; set; }
        public Nullable<int> element_type { get; set; }
        public Nullable<int> id_category { get; set; }
        public Nullable<int> id_assessment { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
