//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class special_metric_master
    {
        public int id_speacial_metric { get; set; }
        public string metric_value { get; set; }
        public Nullable<int> id_theme { get; set; }
        public Nullable<int> metric_type { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
    }
}
