//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_brief_enquiry
    {
        public int id_enquiry { get; set; }
        public string name { get; set; }
        public string mail { get; set; }
        public string phone { get; set; }
        public string brief_title { get; set; }
        public string enquiry { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> update_date_time { get; set; }
    }
}
