//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_temp_user_upload
    {
        public int id_temp_user_upload { get; set; }
        public string temp_user_upload_key { get; set; }
        public string EMPLOYEEID { get; set; }
        public string ROLE { get; set; }
        public Nullable<int> ID_ROLE { get; set; }
        public string USERID { get; set; }
        public string PASSWORD { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string AGE { get; set; }
        public string EMAIL { get; set; }
        public string MOBILE { get; set; }
        public string GENDER { get; set; }
        public string CITY { get; set; }
        public string OFFICE_ADDRESS { get; set; }
        public string DATE_OF_BIRTH { get; set; }
        public string DATE_OF_JOINING { get; set; }
        public string user_department { get; set; }
        public string user_designation { get; set; }
        public string user_function { get; set; }
        public string user_grade { get; set; }
        public string user_status { get; set; }
        public string reporting_manager { get; set; }
        public Nullable<int> id_reporting_manager { get; set; }
        public string status { get; set; }
    }
}
