//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_job
    {
        public int id_job { get; set; }
        public Nullable<int> id_organization { get; set; }
        public string compname { get; set; }
        public string phone { get; set; }
        public Nullable<int> jobcategory { get; set; }
        public string jobtitle { get; set; }
        public Nullable<int> minsalary { get; set; }
        public Nullable<int> maxsalary { get; set; }
        public Nullable<int> noofopen { get; set; }
        public string gender { get; set; }
        public string minquali { get; set; }
        public string englishreq { get; set; }
        public string experience { get; set; }
        public string jobdesc { get; set; }
        public string jobrequiremnt { get; set; }
        public string jobtiming { get; set; }
        public string name { get; set; }
        public string shift { get; set; }
        public string mailid { get; set; }
        public string state { get; set; }
        public string save_type { get; set; }
        public string city { get; set; }
        public string area { get; set; }
        public Nullable<System.DateTime> expdate { get; set; }
        public string jobtype { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public Nullable<int> jobpoints { get; set; }
        public string desc_name { get; set; }
        public Nullable<int> desc_status { get; set; }
        public Nullable<int> experiance_month { get; set; }
        public Nullable<int> experiance_year { get; set; }
        public Nullable<int> id_ce_evaluation_jobindustry { get; set; }
        public string skillminifest_status { get; set; }
        public string pdf_cv { get; set; }
        public string video_cv { get; set; }
        public string cv_not_required { get; set; }
        public string job_point_name { get; set; }
        public string is_interview { get; set; }
    }
}
