//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_color_config
    {
        public int id_color_config { get; set; }
        public Nullable<int> id_organisation { get; set; }
        public Nullable<int> config_type { get; set; }
        public string grid1_bk_color { get; set; }
        public string grid1_text_color { get; set; }
        public string grid2_bk_color { get; set; }
        public string grid2_text_color { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_date_time { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
