//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_content_answer_default
    {
        public int ID_CONTENT_ANSWER { get; set; }
        public int ID_CONTENT { get; set; }
        public string CONTENT_ANSWER_TITLE { get; set; }
        public string CONTENT_ANSWER_HEADER { get; set; }
        public string CONTENT_ANSWER1 { get; set; }
        public string CONTENT_ANSWER2 { get; set; }
        public string CONTENT_ANSWER3 { get; set; }
        public string CONTENT_ANSWER4 { get; set; }
        public string CONTENT_ANSWER_IMG1 { get; set; }
        public string CONTENT_ANSWER_IMG2 { get; set; }
        public string CONTENT_ANSWER_IMG3 { get; set; }
        public string CONTENT_ANSWER_BANNER { get; set; }
        public string REDIRECTION_URL { get; set; }
        public int CONTENT_ANSWER_COUNTER { get; set; }
        public string STATUS { get; set; }
        public System.DateTime UPDATEDTIME { get; set; }
        public string CONTENT_ANSWER10 { get; set; }
        public string CONTENT_ANSWER5 { get; set; }
        public string CONTENT_ANSWER6 { get; set; }
        public string CONTENT_ANSWER7 { get; set; }
        public string CONTENT_ANSWER8 { get; set; }
        public string CONTENT_ANSWER9 { get; set; }
        public string CONTENT_ANSWER_IMG10 { get; set; }
        public string CONTENT_ANSWER_IMG4 { get; set; }
        public string CONTENT_ANSWER_IMG5 { get; set; }
        public string CONTENT_ANSWER_IMG6 { get; set; }
        public string CONTENT_ANSWER_IMG7 { get; set; }
        public string CONTENT_ANSWER_IMG8 { get; set; }
        public string CONTENT_ANSWER_IMG9 { get; set; }
    }
}
