//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ce_industry
    {
        public int id_ce_industry { get; set; }
        public string id_organization { get; set; }
        public string ce_industry { get; set; }
        public Nullable<int> id_ce_industry_role { get; set; }
        public Nullable<int> role_job_point { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
