//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_assessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_assessment()
        {
            this.tbl_assessment_sheet = new HashSet<tbl_assessment_sheet>();
        }
    
        public int id_assessment { get; set; }
        public string assessment_title { get; set; }
        public string assesment_description { get; set; }
        public Nullable<int> id_organization { get; set; }
        public Nullable<int> assessment_type { get; set; }
        public Nullable<System.DateTime> assess_created { get; set; }
        public Nullable<System.DateTime> assess_start { get; set; }
        public Nullable<System.DateTime> assess_ended { get; set; }
        public string assess_type { get; set; }
        public Nullable<int> assess_group { get; set; }
        public string lower_title { get; set; }
        public string high_title { get; set; }
        public string lower_value { get; set; }
        public string high_value { get; set; }
        public Nullable<int> total_attempt { get; set; }
        public Nullable<int> ans_requiered { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public string answer_description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_assessment_sheet> tbl_assessment_sheet { get; set; }
        public virtual tbl_organization tbl_organization { get; set; }
    }
}
