//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_entrepreneurship_master
    {
        public int id_entrepreneurship { get; set; }
        public string company_name { get; set; }
        public string founders { get; set; }
        public string foundation_date { get; set; }
        public string reason { get; set; }
        public Nullable<int> id_buisiness_stage { get; set; }
        public string revenue { get; set; }
        public string far_from_launch { get; set; }
        public string company_structure { get; set; }
        public string buisiness_stage_others { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public string product_code { get; set; }
        public string website { get; set; }
        public Nullable<int> id_user { get; set; }
    }
}
