//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_category()
        {
            this.tbl_category_associantion = new HashSet<tbl_category_associantion>();
            this.tbl_content_organization_mapping = new HashSet<tbl_content_organization_mapping>();
        }
    
        public int ID_CATEGORY { get; set; }
        public int ID_ORGANIZATION { get; set; }
        public string CATEGORYNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string IMAGE_PATH { get; set; }
        public string STATUS { get; set; }
        public System.DateTime UPDATED_DATE_TIME { get; set; }
        public string SUB_HEADING { get; set; }
        public Nullable<int> ORDERID { get; set; }
        public Nullable<int> IS_PRIMARY { get; set; }
        public Nullable<int> ID_PARENT { get; set; }
        public Nullable<int> SEARCH_MAX_COUNT { get; set; }
        public Nullable<int> COUNT_REQUIRED { get; set; }
        public Nullable<int> CATEGORY_TYPE { get; set; }
        public string IMAGE_URL { get; set; }
        public Nullable<int> id_default { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_category_associantion> tbl_category_associantion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_content_organization_mapping> tbl_content_organization_mapping { get; set; }
        public virtual tbl_organization tbl_organization { get; set; }
    }
}
