//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_content_answer_steps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_content_answer_steps()
        {
            this.tbl_survey = new HashSet<tbl_survey>();
        }
    
        public int ID_ANSWER_STEP { get; set; }
        public int ID_CONTENT_ANSWER { get; set; }
        public int STEPNO { get; set; }
        public string ANSWER_STEPS_PART1 { get; set; }
        public string ANSWER_STEPS_PART2 { get; set; }
        public string ANSWER_STEPS_IMG1 { get; set; }
        public string ANSWER_STEPS_IMG2 { get; set; }
        public string ANSWER_STEPS_BANNER { get; set; }
        public string REDIRECTION_URL { get; set; }
        public string STATUS { get; set; }
        public System.DateTime UPDATEDDATETIME { get; set; }
        public Nullable<int> ID_THEME { get; set; }
        public string ANSWER_STEPS_PART3 { get; set; }
        public string ANSWER_STEPS_IMG3 { get; set; }
        public string ANSWER_STEPS_IMG10 { get; set; }
        public string ANSWER_STEPS_IMG5 { get; set; }
        public string ANSWER_STEPS_IMG6 { get; set; }
        public string ANSWER_STEPS_IMG7 { get; set; }
        public string ANSWER_STEPS_IMG8 { get; set; }
        public string ANSWER_STEPS_IMG9 { get; set; }
        public string ANSWER_STEPS_PART10 { get; set; }
        public string ANSWER_STEPS_PART4 { get; set; }
        public string ANSWER_STEPS_PART5 { get; set; }
        public string ANSWER_STEPS_PART6 { get; set; }
        public string ANSWER_STEPS_PART7 { get; set; }
        public string ANSWER_STEPS_PART8 { get; set; }
        public string ANSWER_STEPS_PART9 { get; set; }
        public string ANSWER_STEPS_IMG4 { get; set; }
    
        public virtual tbl_content_answer tbl_content_answer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_survey> tbl_survey { get; set; }
    }
}
