//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rs_type_qna
    {
        public int id_rs_type_qna { get; set; }
        public Nullable<int> id_assessment_log { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_organization { get; set; }
        public Nullable<int> id_assessment_sheet { get; set; }
        public Nullable<int> id_assessment { get; set; }
        public Nullable<int> attempt_number { get; set; }
        public Nullable<int> total_question { get; set; }
        public Nullable<int> right_answer_count { get; set; }
        public Nullable<int> wrong_answer_count { get; set; }
        public Nullable<double> result_in_percentage { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
