//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_log_master
    {
        public int id_log { get; set; }
        public Nullable<int> id_user { get; set; }
        public string is_registered { get; set; }
        public Nullable<int> academic_tiles { get; set; }
        public Nullable<int> study_abroad { get; set; }
        public Nullable<int> job { get; set; }
        public Nullable<int> entrepreneurship { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
