//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rewards_redeem_master
    {
        public int id_rewards { get; set; }
        public string AccountID { get; set; }
        public string EmailAddress { get; set; }
        public string PartnerCode { get; set; }
        public string ProviderCode { get; set; }
        public string RedeemType { get; set; }
        public string TotalPoints { get; set; }
        public string TransactionID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_org { get; set; }
        public Nullable<int> id_game { get; set; }
    }
}
