//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_assessment_audit
    {
        public int id_assessment_audit { get; set; }
        public Nullable<int> id_assessment { get; set; }
        public Nullable<int> id_assessment_sheet { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_assessment_question { get; set; }
        public Nullable<int> id_assessment_answer { get; set; }
        public Nullable<int> value_sent { get; set; }
        public Nullable<int> attempt_no { get; set; }
        public Nullable<System.DateTime> recorded_timestamp { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
