//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_job_email_template_body
    {
        public int template_id { get; set; }
        public string template_name { get; set; }
        public Nullable<int> template_unique_id { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
    }
}
