//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sso_log
    {
        public int id_sso_log { get; set; }
        public string tran_id { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string userid { get; set; }
    }
}
