//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_scheduled_event_subscription_log
    {
        public int id_scheduled_event_subscription_log { get; set; }
        public Nullable<int> id_scheduled_event { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_cms_user { get; set; }
        public Nullable<int> id_organization { get; set; }
        public Nullable<System.DateTime> event_sent_timestamp { get; set; }
        public Nullable<int> event_user_response { get; set; }
        public Nullable<System.DateTime> event_user_response_timestamp { get; set; }
        public string event_user_comment { get; set; }
        public Nullable<int> apporoved_reporting_manager { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string subscription_status { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
