//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_content_counters
    {
        public int id_content_counters { get; set; }
        public Nullable<int> id_content { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
