//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_theme_leagues
    {
        public int id_league { get; set; }
        public Nullable<int> id_theme { get; set; }
        public string league_name { get; set; }
        public string league_logo { get; set; }
        public string status { get; set; }
        public Nullable<int> id_org { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> level { get; set; }
    }
}
