//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_popup_info_mapping
    {
        public int id_popup_info_mapping { get; set; }
        public Nullable<int> id_popup_info { get; set; }
        public string popup_info_detail { get; set; }
        public Nullable<int> popup_info_seq { get; set; }
        public string popup_image_element { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> createddatetime { get; set; }
    }
}
