//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_couponsredeemed
    {
        public int id_CouponsRedeemed { get; set; }
        public string CouponID { get; set; }
        public string WebsiteName { get; set; }
        public string CouponCode { get; set; }
        public string CouponDescription { get; set; }
        public string Link { get; set; }
        public string PointsUsed { get; set; }
        public string Image { get; set; }
        public string ExpiryDate { get; set; }
        public Nullable<int> id_game { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_org { get; set; }
        public string status { get; set; }
        public Nullable<int> usedmoney { get; set; }
    }
}
