//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_email_feedback_user
    {
        public int id_feedback_user { get; set; }
        public Nullable<int> id_role { get; set; }
        public string emp_emailID { get; set; }
        public string emp_name { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
