//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_notification_reminder
    {
        public int id_notification_reminder { get; set; }
        public Nullable<int> id_notification { get; set; }
        public Nullable<int> id_reminder_notification { get; set; }
        public Nullable<int> reminder_timeout { get; set; }
        public Nullable<int> reminder_frequency { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
