//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mail_verification
    {
        public int id_verification { get; set; }
        public string OTP { get; set; }
        public Nullable<int> id_organization { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_datettime { get; set; }
    }
}
