//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_banner_config_master
    {
        public int id_banner_config { get; set; }
        public string banner_name { get; set; }
        public Nullable<int> banner_location { get; set; }
        public Nullable<int> banner_position { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> banner_type { get; set; }
        public List<tbl_banner_body> body_value { get; set; }
    }
}
