//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_content()
        {
            this.tbl_content_banner = new HashSet<tbl_content_banner>();
            this.tbl_content_header_footer = new HashSet<tbl_content_header_footer>();
            this.tbl_content_right_association = new HashSet<tbl_content_right_association>();
            this.tbl_content_organization_mapping = new HashSet<tbl_content_organization_mapping>();
            this.tbl_subscriptions = new HashSet<tbl_subscriptions>();
        }
    
        public int ID_CONTENT { get; set; }
        public int ID_THEME { get; set; }
        public int ID_USER { get; set; }
        public int ID_CONTENT_LEVEL { get; set; }
        public string CONTENT_TITLE { get; set; }
        public string CONTENT_HEADER { get; set; }
        public string CONTENT_QUESTION { get; set; }
        public int CONTENT_COUNTER { get; set; }
        public string STATUS { get; set; }
        public System.DateTime UPDATED_DATE_TIME { get; set; }
        public int LINK_COUNT { get; set; }
        public int IS_PRIMARY { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public string COMMENT { get; set; }
        public string CONTENT_IDENTIFIER { get; set; }
        public int CONTENT_OWNER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_content_banner> tbl_content_banner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_content_header_footer> tbl_content_header_footer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_content_right_association> tbl_content_right_association { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_content_organization_mapping> tbl_content_organization_mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_subscriptions> tbl_subscriptions { get; set; }
    }
}
