//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_subscriber_attendance
    {
        public int id_attendance { get; set; }
        public Nullable<int> id_user { get; set; }
        public string subscriber_name { get; set; }
        public Nullable<int> id_batch { get; set; }
        public string batch_time { get; set; }
        public Nullable<int> id_event { get; set; }
        public Nullable<int> id_org { get; set; }
        public Nullable<int> id_facilitator { get; set; }
        public Nullable<int> rating { get; set; }
        public string attendance_status { get; set; }
    }
}
