//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sul_seminar_master
    {
        public int id_seminar { get; set; }
        public string title { get; set; }
        public string objective { get; set; }
        public string stream { get; set; }
        public Nullable<System.DateTime> seminar_start_time { get; set; }
        public Nullable<System.DateTime> seminar_end_time { get; set; }
        public string seminar_duration { get; set; }
        public string speaker_name { get; set; }
        public string speaker_organisation { get; set; }
        public string location { get; set; }
        public Nullable<int> user_count { get; set; }
        public string seminar_status { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> update_date_time { get; set; }
        public Nullable<int> fest_type { get; set; }
        public Nullable<int> time_interval { get; set; }
    }
}
