//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_job_reject_feedback_log
    {
        public int feedback_id { get; set; }
        public Nullable<int> id_job { get; set; }
        public Nullable<int> id_user { get; set; }
        public string starRating { get; set; }
        public string feedback { get; set; }
        public Nullable<int> round_number { get; set; }
        public Nullable<System.DateTime> updated_time { get; set; }
    }
}
