//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cv_education
    {
        public int id_cv_education { get; set; }
        public Nullable<int> id_cv { get; set; }
        public Nullable<int> id_user { get; set; }
        public string college { get; set; }
        public string degree { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string summary { get; set; }
    }
}
