//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_game_group_association
    {
        public int id_game_group_association { get; set; }
        public Nullable<int> id_game { get; set; }
        public Nullable<int> association_type { get; set; }
        public Nullable<int> id_game_group { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_organization { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<System.DateTime> removed_date { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<int> assigned_by { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
