//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_organization()
        {
            this.tbl_assessment = new HashSet<tbl_assessment>();
            this.tbl_assessment_general = new HashSet<tbl_assessment_general>();
            this.tbl_assessment_sheet = new HashSet<tbl_assessment_sheet>();
            this.tbl_banner = new HashSet<tbl_banner>();
            this.tbl_category = new HashSet<tbl_category>();
            this.tbl_category_tiles = new HashSet<tbl_category_tiles>();
            this.tbl_content_organization_mapping = new HashSet<tbl_content_organization_mapping>();
            this.tbl_content_right_association = new HashSet<tbl_content_right_association>();
            this.tbl_csst_role = new HashSet<tbl_csst_role>();
            this.tbl_organisation_banner = new HashSet<tbl_organisation_banner>();
            this.tbl_role = new HashSet<tbl_role>();
        }
    
        public int ID_ORGANIZATION { get; set; }
        public int ID_INDUSTRY { get; set; }
        public int ID_BUSINESS_TYPE { get; set; }
        public string ORGANIZATION_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string LOGO { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACTNUMBER { get; set; }
        public string CONTACTEMAIL { get; set; }
        public string DEFAULT_EMAIL { get; set; }
        public string STATUS { get; set; }
        public System.DateTime UPDATED_DATE_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_assessment> tbl_assessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_assessment_general> tbl_assessment_general { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_assessment_sheet> tbl_assessment_sheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_banner> tbl_banner { get; set; }
        public virtual tbl_business_type tbl_business_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_category> tbl_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_category_tiles> tbl_category_tiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_content_organization_mapping> tbl_content_organization_mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_content_right_association> tbl_content_right_association { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_csst_role> tbl_csst_role { get; set; }
        public virtual tbl_industry tbl_industry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_organisation_banner> tbl_organisation_banner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_role> tbl_role { get; set; }
    }
}
