//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_currency_data
    {
        public int id_currency_data { get; set; }
        public Nullable<int> id_game { get; set; }
        public Nullable<int> id_badge { get; set; }
        public Nullable<int> id_org { get; set; }
        public Nullable<int> currency_value { get; set; }
        public Nullable<int> id_currency { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public Nullable<int> id_metric { get; set; }
        public Nullable<int> id_money { get; set; }
        public Nullable<int> money_value { get; set; }
        public string money_name { get; set; }
    }
}
