//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sul_seminar_timeslot
    {
        public int id_slot { get; set; }
        public Nullable<int> time_slot_start_time_hour { get; set; }
        public Nullable<int> time_slot_start_time_minute { get; set; }
        public Nullable<int> time_slot_end_time_hour { get; set; }
        public Nullable<int> time_slot_end_time_minute { get; set; }
        public string session_start_time { get; set; }
        public string session_end_time { get; set; }
        public Nullable<int> id_seminar { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> update_date_time { get; set; }
    }
}
