//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_content_right_association
    {
        public int id_content_right_association { get; set; }
        public int id_content { get; set; }
        public int id_organization { get; set; }
        public Nullable<System.DateTime> content_expiry_date { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> real_content_id { get; set; }
        public Nullable<int> real_organization_id { get; set; }
        public Nullable<System.DateTime> transfered_date { get; set; }
    
        public virtual tbl_content tbl_content { get; set; }
        public virtual tbl_organization tbl_organization { get; set; }
    }
}
