//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_brief_user_assignment
    {
        public int id_brief_user_assignment { get; set; }
        public Nullable<int> id_brief_master { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<System.DateTime> assignment_datetime { get; set; }
        public string assignment_status { get; set; }
        public Nullable<System.DateTime> scheduled_datetime { get; set; }
        public string scheduled_status { get; set; }
        public Nullable<System.DateTime> published_datetime { get; set; }
        public string published_status { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
