//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_content_program_mapping
    {
        public int id_content_program_mapping { get; set; }
        public Nullable<int> id_organization { get; set; }
        public Nullable<int> id_category { get; set; }
        public Nullable<int> id_assessment_sheet { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_role { get; set; }
        public Nullable<int> map_type { get; set; }
        public Nullable<int> option_type { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<int> id_category_tile { get; set; }
        public Nullable<int> id_category_heading { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
