//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_college_list
    {
        public int id_college { get; set; }
        public string college_name { get; set; }
        public string clg_city { get; set; }
        public string clg_state { get; set; }
        public string clg_phone { get; set; }
        public string status { get; set; }
        public Nullable<int> id_city { get; set; }
        public Nullable<int> id_organization { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
    }
}
