//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cv_additional_info
    {
        public int id_cv_additional { get; set; }
        public Nullable<int> id_cv { get; set; }
        public Nullable<int> id_user { get; set; }
        public string skills { get; set; }
        public string languages { get; set; }
        public string intrests { get; set; }
        public string linkedin { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public string blog { get; set; }
        public string others { get; set; }
        public string refrences { get; set; }
        public string awards { get; set; }
    }
}
