//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_authcode
    {
        public int ID_CODE { get; set; }
        public string CODE { get; set; }
        public System.DateTime UPDATEDTIME { get; set; }
        public string STATUS { get; set; }
    }
}
