//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_academic_tiles
    {
        public int id_academic_tile { get; set; }
        public string tile_name { get; set; }
        public string tile_image { get; set; }
        public Nullable<int> tile_position { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> id_org { get; set; }
        public string tile_description { get; set; }
        public Nullable<int> theme_id { get; set; }
        public string url { get; set; }
    }
}
