//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_category_tiles_default
    {
        public int id_category_tiles { get; set; }
        public string tile_heading { get; set; }
        public Nullable<int> category_theme { get; set; }
        public Nullable<int> id_organization { get; set; }
        public string tile_image { get; set; }
        public string status { get; set; }
        public System.DateTime updated_date_time { get; set; }
        public Nullable<int> category_order { get; set; }
        public string image_url { get; set; }
        public Nullable<int> id_default { get; set; }
    }
}
