//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_job_preferences
    {
        public int id_job_preference { get; set; }
        public Nullable<int> id_location { get; set; }
        public string job_type { get; set; }
        public Nullable<int> experience_years { get; set; }
        public Nullable<int> experience_months { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> id_user { get; set; }
    }
}
