//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_relegtion_data
    {
        public int id_relegation { get; set; }
        public Nullable<int> id_game { get; set; }
        public Nullable<int> id_org { get; set; }
        public Nullable<int> id_league { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> relegation_frequency { get; set; }
        public string frequency_type { get; set; }
        public Nullable<int> relegation_method { get; set; }
        public Nullable<int> relegation_expression { get; set; }
        public Nullable<int> min_score { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public Nullable<int> id_metric { get; set; }
    }
}
