//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_badge_reward_mapping
    {
        public int id_mapping { get; set; }
        public Nullable<int> id_org { get; set; }
        public Nullable<int> id_theme { get; set; }
        public Nullable<int> id_badge { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public Nullable<int> id_reward { get; set; }
        public string reward_name { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string badge_name { get; set; }
    }
}
