//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_brief_user_feedback_master
    {
        public int id_feedback { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> OID { get; set; }
        public Nullable<int> liked { get; set; }
        public Nullable<int> disliked { get; set; }
        public string reason { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> feedback_type { get; set; }
        public Nullable<int> id_brief_master { get; set; }
    }
}
