//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_feedback_master
    {
        public int id_feedback { get; set; }
        public Nullable<int> Issues { get; set; }
        public Nullable<int> Suggestions { get; set; }
        public Nullable<int> Content { get; set; }
        public Nullable<int> UI { get; set; }
        public string Description { get; set; }
        public Nullable<int> MediaFlag { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public string Contact { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> OID { get; set; }
        public string FIRSTNAME { get; set; }
        public List<string> file { get; set; }
    }
}
