//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_childinformation
    {
        public int id_child { get; set; }
        public string roll_no { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string sur_name { get; set; }
        public string year { get; set; }
        public string id_organization { get; set; }
        public string id_teacher { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<System.DateTime> doj { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string pincode { get; set; }
        public string father_name { get; set; }
        public string father_mob { get; set; }
        public string mother_name { get; set; }
        public string mother_mob { get; set; }
        public string email_id { get; set; }
        public string other_contact_name { get; set; }
        public string other_contact_mob { get; set; }
        public string remarks_med_alergies { get; set; }
        public string identification_marks { get; set; }
        public string payment_term1 { get; set; }
        public string payment_term2 { get; set; }
    }
}
