//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_zone
    {
        public int id_user_zone { get; set; }
        public Nullable<int> id_user_zone_master { get; set; }
        public Nullable<int> id_organization { get; set; }
        public string location { get; set; }
        public string status { get; set; }
        public string updated_date_time { get; set; }
    }
}
