//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_facilitator_users
    {
        public int ID_USER { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string STATUS { get; set; }
        public System.DateTime created_datetime { get; set; }
        public Nullable<System.DateTime> modified_datetime { get; set; }
        public string employee_id { get; set; }
        public string image_path { get; set; }
    }
}
