//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_landing_page
    {
        public int Landingpage_log_no { get; set; }
        public Nullable<int> Landingpage_sl_no { get; set; }
        public Nullable<int> Landingpage_sort_order { get; set; }
        public Nullable<int> landingpage_theme { get; set; }
        public string Landingpage_redirect_URL { get; set; }
        public string Landingpage_name { get; set; }
        public string Landingpage_description { get; set; }
        public string Landingpage_status { get; set; }
        public Nullable<System.DateTime> Landingpage_createddate { get; set; }
        public Nullable<System.DateTime> landingpage_updatedate { get; set; }
    }
}
