//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_job_zoom_meeting_id
    {
        public int zoom_id { get; set; }
        public string meetingNumber { get; set; }
        public string apiKey { get; set; }
        public string apiSecret { get; set; }
        public string password { get; set; }
        public string isStatusActive { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_job { get; set; }
        public Nullable<int> round_number { get; set; }
        public Nullable<int> ID_ORGANIZATION { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<System.DateTime> issue_datetime { get; set; }
        public string encrypt_pwd { get; set; }
    }
}
