//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_content_answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_content_answer()
        {
            this.tbl_content_answer_steps = new HashSet<tbl_content_answer_steps>();
            this.tbl_content_metadata = new HashSet<tbl_content_metadata>();
            this.tbl_content_type_link = new HashSet<tbl_content_type_link>();
            this.tbl_survey = new HashSet<tbl_survey>();
        }
    
        public int ID_CONTENT_ANSWER { get; set; }
        public int ID_CONTENT { get; set; }
        public string CONTENT_ANSWER_TITLE { get; set; }
        public string CONTENT_ANSWER_HEADER { get; set; }
        public string CONTENT_ANSWER1 { get; set; }
        public string CONTENT_ANSWER2 { get; set; }
        public string CONTENT_ANSWER3 { get; set; }
        public string CONTENT_ANSWER4 { get; set; }
        public string CONTENT_ANSWER_IMG1 { get; set; }
        public string CONTENT_ANSWER_IMG2 { get; set; }
        public string CONTENT_ANSWER_IMG3 { get; set; }
        public string CONTENT_ANSWER_BANNER { get; set; }
        public string REDIRECTION_URL { get; set; }
        public int CONTENT_ANSWER_COUNTER { get; set; }
        public string STATUS { get; set; }
        public System.DateTime UPDATEDTIME { get; set; }
        public string CONTENT_ANSWER10 { get; set; }
        public string CONTENT_ANSWER5 { get; set; }
        public string CONTENT_ANSWER6 { get; set; }
        public string CONTENT_ANSWER7 { get; set; }
        public string CONTENT_ANSWER8 { get; set; }
        public string CONTENT_ANSWER9 { get; set; }
        public string CONTENT_ANSWER_IMG10 { get; set; }
        public string CONTENT_ANSWER_IMG4 { get; set; }
        public string CONTENT_ANSWER_IMG5 { get; set; }
        public string CONTENT_ANSWER_IMG6 { get; set; }
        public string CONTENT_ANSWER_IMG7 { get; set; }
        public string CONTENT_ANSWER_IMG8 { get; set; }
        public string CONTENT_ANSWER_IMG9 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_content_answer_steps> tbl_content_answer_steps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_content_metadata> tbl_content_metadata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_content_type_link> tbl_content_type_link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_survey> tbl_survey { get; set; }
    }
}
