//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_content_header_footer
    {
        public int id_content_header_footer { get; set; }
        public int id_content { get; set; }
        public Nullable<int> id_header { get; set; }
        public Nullable<int> id_footer { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    
        public virtual tbl_content tbl_content { get; set; }
        public virtual tbl_content_footer tbl_content_footer { get; set; }
        public virtual tbl_content_header tbl_content_header { get; set; }
    }
}
