//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_profile
    {
        public int ID_PROFILE { get; set; }
        public int ID_USER { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public Nullable<int> AGE { get; set; }
        public string LOCATION { get; set; }
        public string EMAIL { get; set; }
        public string MOBILE { get; set; }
        public string GENDER { get; set; }
        public string DESIGNATION { get; set; }
        public string CITY { get; set; }
        public string OFFICE_ADDRESS { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public Nullable<System.DateTime> DATE_OF_JOINING { get; set; }
        public string REPORTING_MANAGER { get; set; }
        public string PROFILE_IMAGE { get; set; }
        public string COLLEGE { get; set; }
        public string GRADUATIONYEAR { get; set; }
        public string STATE { get; set; }
        public Nullable<int> ResumeFlag { get; set; }
        public string ResumeLocation { get; set; }
        public Nullable<int> id_degree { get; set; }
        public Nullable<int> id_stream { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<int> STUDENT { get; set; }
        public Nullable<int> NOTSTUDENT { get; set; }
        public string OTHERSTREAM { get; set; }
        public Nullable<int> id_foundation { get; set; }
        public string clg_city { get; set; }
        public string clg_state { get; set; }
        public string clg_country { get; set; }
        public Nullable<int> social_dp_flag { get; set; }
    }
}
