//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ce_evalution_answer_key_setup
    {
        public int id_ce_evalution_answer_key_setup { get; set; }
        public Nullable<int> id_organization { get; set; }
        public string akcode { get; set; }
        public string key_code { get; set; }
        public string answer_key { get; set; }
        public string description { get; set; }
        public string image_path { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
