//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sul_fest_master
    {
        public int id_event { get; set; }
        public string event_title { get; set; }
        public string event_objective { get; set; }
        public string event_logo { get; set; }
        public Nullable<int> is_registration_needed { get; set; }
        public System.DateTime registration_start_date { get; set; }
        public System.DateTime registration_end_date { get; set; }
        public System.DateTime event_start_date { get; set; }
        public System.DateTime event_end_date { get; set; }
        public string event_duration { get; set; }
        public string location_text { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string cityname { get; set; }
        public string address { get; set; }
        public Nullable<int> is_event_closed { get; set; }
        public Nullable<int> user_count { get; set; }
        public Nullable<int> is_college_restricted { get; set; }
        public Nullable<int> id_college { get; set; }
        public Nullable<int> is_paid_event { get; set; }
        public Nullable<int> is_org_specified { get; set; }
        public Nullable<int> id_org { get; set; }
        public Nullable<int> is_sponsor_available { get; set; }
        public Nullable<int> id_sponsor { get; set; }
        public string sponsor_logo { get; set; }
        public string event_status { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public string amount { get; set; }
        public string contact_name { get; set; }
        public string contact_number { get; set; }
    }
}
