//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_badge_master
    {
        public int id_badge { get; set; }
        public Nullable<int> id_theme { get; set; }
        public string badge_name { get; set; }
        public string badge_logo { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
    }
}
