//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee_strength_master
    {
        public int employee_strength_id { get; set; }
        public string employee_strength_data { get; set; }
        public Nullable<System.DateTime> updated_time { get; set; }
    }
}
