//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reminder_notification_config
    {
        public int id_reminder_notification_config { get; set; }
        public Nullable<int> id_notification { get; set; }
        public Nullable<int> reminder_type { get; set; }
        public Nullable<int> DH { get; set; }
        public Nullable<int> YH { get; set; }
        public Nullable<int> YM { get; set; }
        public Nullable<int> TM { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
