//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_non_disclousure_clause_content
    {
        public int id_clause_content { get; set; }
        public Nullable<int> id_org { get; set; }
        public string content_title { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> id_creator { get; set; }
        public string status { get; set; }
    }
}
