//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cv_personel_info
    {
        public int id_cv_personel_info { get; set; }
        public Nullable<int> id_cv { get; set; }
        public Nullable<int> id_user { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string day { get; set; }
        public string month { get; set; }
        public string about { get; set; }
        public string year { get; set; }
    }
}
