//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_scheduled_event
    {
        public int id_scheduled_event { get; set; }
        public Nullable<int> id_organization { get; set; }
        public Nullable<int> id_event_creator { get; set; }
        public string event_title { get; set; }
        public string event_description { get; set; }
        public Nullable<System.DateTime> registration_start_date { get; set; }
        public Nullable<System.DateTime> registration_end_date { get; set; }
        public Nullable<System.DateTime> event_start_datetime { get; set; }
        public string event_duration { get; set; }
        public Nullable<int> event_type { get; set; }
        public Nullable<int> event_group_type { get; set; }
        public string program_name { get; set; }
        public string program_description { get; set; }
        public string program_objective { get; set; }
        public string facilitator_name { get; set; }
        public string facilitator_organization { get; set; }
        public string program_image { get; set; }
        public Nullable<int> no_of_participants { get; set; }
        public string program_venue { get; set; }
        public string program_location { get; set; }
        public Nullable<int> attachment_type { get; set; }
        public Nullable<int> id_program { get; set; }
        public Nullable<int> id_assessment { get; set; }
        public Nullable<int> id_category_tile { get; set; }
        public Nullable<int> id_category_heading { get; set; }
        public Nullable<int> id_category { get; set; }
        public string is_approval { get; set; }
        public string is_response { get; set; }
        public string is_unsubscribe { get; set; }
        public Nullable<System.DateTime> program_start_date { get; set; }
        public Nullable<int> program_duration_type { get; set; }
        public Nullable<int> program_duration { get; set; }
        public string program_duration_unit { get; set; }
        public Nullable<System.DateTime> program_end_date { get; set; }
        public string event_additional_info { get; set; }
        public string event_online_url { get; set; }
        public string participant_level { get; set; }
        public string event_comment { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public string location { get; set; }
        public Nullable<int> id_facilitator { get; set; }
    }
}
