//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_color_config_flag
    {
        public int id_flag { get; set; }
        public Nullable<int> id_org { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
