//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_job_publish_calender_report
    {
        public int publish_id { get; set; }
        public Nullable<int> id_job { get; set; }
        public Nullable<int> round_number { get; set; }
        public Nullable<int> interview_id { get; set; }
        public string publishDate { get; set; }
        public string publishFromTime { get; set; }
        public string publishToTime { get; set; }
        public string publishSlots { get; set; }
        public string publishStatus { get; set; }
        public Nullable<int> publishInterval { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
        public Nullable<System.DateTime> created_datetime { get; set; }
    }
}
