//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_certificate_configure_data
    {
        public int id_configure_data { get; set; }
        public int id_certificate { get; set; }
        public Nullable<int> id_organization { get; set; }
        public string label_1 { get; set; }
        public string label_2 { get; set; }
        public string label_3 { get; set; }
        public string label_1_range { get; set; }
        public string label_2_range { get; set; }
        public string label_3_range { get; set; }
        public string signature { get; set; }
    }
}
