//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_content_default
    {
        public int ID_CONTENT { get; set; }
        public Nullable<int> ID_THEME { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<int> ID_CONTENT_LEVEL { get; set; }
        public string CONTENT_TITLE { get; set; }
        public string CONTENT_HEADER { get; set; }
        public string CONTENT_QUESTION { get; set; }
        public Nullable<int> CONTENT_COUNTER { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE_TIME { get; set; }
        public int LINK_COUNT { get; set; }
        public int IS_PRIMARY { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public string COMMENT { get; set; }
        public string CONTENT_IDENTIFIER { get; set; }
        public int CONTENT_OWNER { get; set; }
    }
}
