//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_brief_master_body
    {
        public int id_brief_master_body { get; set; }
        public Nullable<int> id_brief_master { get; set; }
        public string brief_code { get; set; }
        public string brief_template { get; set; }
        public string brief_destination { get; set; }
        public string resource_number { get; set; }
        public Nullable<int> srno { get; set; }
        public Nullable<int> resource_type { get; set; }
        public string resouce_data { get; set; }
        public string resouce_code { get; set; }
        public Nullable<int> media_type { get; set; }
        public string file_type { get; set; }
        public string file_extension { get; set; }
        public string resource_mime { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public string dup_resouce_data { get; set; }
        public string resource_text { get; set; }
        public string dup_resource_text { get; set; }
    }
}
