//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_banner_ad_config
    {
        public int id_banner_ad_config { get; set; }
        public Nullable<int> id_banner_config { get; set; }
        public Nullable<int> id_academic_tile { get; set; }
        public Nullable<int> id_brief_category_tile { get; set; }
        public Nullable<int> brief_number { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
