//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cv_master
    {
        public int id_cv { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> oid { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string status { get; set; }
        public Nullable<int> cv_type { get; set; }
        public string CVRequest { get; set; }
        public string videoname { get; set; }
    }
}
