//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_game_phase
    {
        public int id_game_path { get; set; }
        public Nullable<int> id_game { get; set; }
        public Nullable<int> content_type { get; set; }
        public Nullable<int> id_assessment { get; set; }
        public Nullable<int> id_content { get; set; }
        public Nullable<int> order_no { get; set; }
        public string is_mandatory { get; set; }
        public Nullable<int> weightage { get; set; }
    }
}
