//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_min_qualification_mapping
    {
        public int id_qualification { get; set; }
        public Nullable<int> id_job { get; set; }
        public string minquali { get; set; }
        public Nullable<int> id_min_quali { get; set; }
    }
}
