//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_brief_read_status
    {
        public int id_brief_read_status { get; set; }
        public Nullable<int> id_brief_master { get; set; }
        public Nullable<int> id_organization { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> read_status { get; set; }
        public Nullable<int> action_status { get; set; }
        public Nullable<System.DateTime> read_datetime { get; set; }
        public Nullable<System.DateTime> action_dateime { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
