//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_applied_job
    {
        public int id_application { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_job { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> is_resume_active { get; set; }
        public Nullable<int> view_status { get; set; }
        public Nullable<int> offer_status { get; set; }
        public Nullable<int> offer_accepted_status { get; set; }
    }
}
