//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_game_solo
    {
        public int id_game { get; set; }
        public Nullable<int> id_participatant { get; set; }
        public Nullable<int> participatant_level { get; set; }
    }
}
