//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_organisation_banner
    {
        public int id_organisation_banner { get; set; }
        public string banner_name { get; set; }
        public string Banner_path { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> id_organisation { get; set; }
    
        public virtual tbl_organization tbl_organization { get; set; }
    }
}
