//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_brief_master
    {
        public int id_brief_master { get; set; }
        public Nullable<int> id_organization { get; set; }
        public string brief_title { get; set; }
        public string brief_code { get; set; }
        public string brief_description { get; set; }
        public Nullable<int> brief_type { get; set; }
        public Nullable<int> override_dnd { get; set; }
        public Nullable<int> is_add_question { get; set; }
        public Nullable<int> question_count { get; set; }
        public Nullable<System.DateTime> scheduled_timestamp { get; set; }
        public Nullable<int> id_brief_category { get; set; }
        public Nullable<int> id_brief_sub_category { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> episode_sequence { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> brief_attachment_flag { get; set; }
        public string brief_attachement_url { get; set; }
    }
}
