//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_third_party_right_swipe_m2ost
    {
        public int id_swipe { get; set; }
        public Nullable<int> id_brief { get; set; }
        public Nullable<int> id_category { get; set; }
        public Nullable<int> id_org { get; set; }
        public string status { get; set; }
        public Nullable<int> type { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> id_category_heading { get; set; }
    }
}
