//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_feedback_bank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_feedback_bank()
        {
            this.tbl_feedback_bank_link = new HashSet<tbl_feedback_bank_link>();
            this.tbl_feedback_data = new HashSet<tbl_feedback_data>();
        }
    
        public int ID_FEEDBACK_BANK { get; set; }
        public string FEEDBACK_NAME { get; set; }
        public Nullable<int> id_organization { get; set; }
        public string FEEDBACK_QUESTION { get; set; }
        public string FEEDBACK_CHOICES { get; set; }
        public string FEEDBACK_IMAGE { get; set; }
        public string STATUS { get; set; }
        public System.DateTime UPDATED_DATE_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_feedback_bank_link> tbl_feedback_bank_link { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_feedback_data> tbl_feedback_data { get; set; }
    }
}
