//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mutthi_skill_development_detail
    {
        public int id_mutthi_skill_development_detail { get; set; }
        public Nullable<int> id_mutthi_sheet { get; set; }
        public Nullable<int> id_skill { get; set; }
    }
}
