//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_third_party_app_right_swipe_mapping
    {
        public int id_third_party { get; set; }
        public Nullable<int> id_mapping { get; set; }
        public Nullable<int> third_party_type { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string logo { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
