//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_brief_question
    {
        public int id_brief_question { get; set; }
        public Nullable<int> id_organization { get; set; }
        public string brief_question { get; set; }
        public Nullable<int> id_brief_category { get; set; }
        public Nullable<int> id_brief_sub_category { get; set; }
        public string question_image { get; set; }
        public int question_type { get; set; }
        public Nullable<int> question_theme_type { get; set; }
        public Nullable<int> question_choice_type { get; set; }
        public Nullable<int> question_complexity { get; set; }
        public string complexity_label { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public List<tbl_brief_answer> answer { get; set; }
        public string brief_category_name { get; set; }
        public string brief_subcategory_name { get; set; }
        public string complexity_name { get; set; }
    }
}
