//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_menu_type
    {
        public int id_menu_type { get; set; }
        public Nullable<int> id_organisation { get; set; }
        public Nullable<int> menu_type { get; set; }
    }
}
