//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_excel
    {
        public int slNo { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public string Graduation_year { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Degree { get; set; }
        public string Stream { get; set; }
        public string ReferalCode { get; set; }
        public string ReferalName { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string SocialCode { get; set; }
    }
}
