//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_brief_tile_level_brief_restriction
    {
        public int id_restriction { get; set; }
        public Nullable<int> id_brief_tile { get; set; }
        public Nullable<int> OID { get; set; }
        public Nullable<int> brief_count { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> time { get; set; }
        public Nullable<int> id_academy { get; set; }
    }
}
