//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_brief_answer
    {
        public int id_brief_answer { get; set; }
        public Nullable<int> id_organization { get; set; }
        public Nullable<int> id_brief_question { get; set; }
        public string brief_answer { get; set; }
        public string choice_image { get; set; }
        public Nullable<int> choice_type { get; set; }
        public Nullable<int> is_correct_answer { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
