//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_badge_log
    {
        public int id_badge_log { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_org { get; set; }
        public Nullable<int> id_badge { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> id_game { get; set; }
    }
}
