//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_enquiry_data
    {
        public int id_enquiry { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> enquiry_type { get; set; }
        public string name { get; set; }
        public string mail { get; set; }
        public string phone { get; set; }
        public Nullable<int> enquiry_reason { get; set; }
        public string message { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public string category { get; set; }
    }
}
