//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_video_cv
    {
        public int id_video { get; set; }
        public Nullable<int> id_cv { get; set; }
        public string videoname { get; set; }
        public string extn { get; set; }
        public string status { get; set; }
    }
}
