//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_academy_brief_log
    {
        public int id_log { get; set; }
        public Nullable<int> id_academy { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> OID { get; set; }
        public Nullable<int> id_brief_master { get; set; }
        public Nullable<int> id_category { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string status { get; set; }
    }
}
