//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_assessment_header
    {
        public int id_assessment_header { get; set; }
        public int id_assessment_scoring_key { get; set; }
        public int id_assessment_question { get; set; }
        public Nullable<int> id_assessment_answer { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    
        public virtual tbl_assessment_answer tbl_assessment_answer { get; set; }
        public virtual tbl_assessment_scoring_key tbl_assessment_scoring_key { get; set; }
        public virtual tbl_assessment_question tbl_assessment_question { get; set; }
    }
}
