//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_news_ticker
    {
        public int Id_ticker { get; set; }
        public Nullable<int> Id_org { get; set; }
        public Nullable<int> Id_creator { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string ticker_news { get; set; }
        public string background_color { get; set; }
        public string font_color { get; set; }
    }
}
