//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_signup_config
    {
        public int id_signup_config { get; set; }
        public string reg_name { get; set; }
        public Nullable<int> mandatory { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_datetime { get; set; }
    }
}
