//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_game_master
    {
        public int id_game { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> id_kpi { get; set; }
        public Nullable<int> game_type { get; set; }
        public Nullable<int> id_theme { get; set; }
        public Nullable<int> id_metric { get; set; }
        public Nullable<int> id_org { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> relegation_switch { get; set; }
        public Nullable<int> id_special_metric { get; set; }
        public string assignment_flag { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> metrics_completion_flag { get; set; }
        public Nullable<int> added_metric_count { get; set; }
        public List<int> kpiids { get; set; }
        public string metricname { get; set; }
    }    
}
