//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_report_content
    {
        public int ID_REPORT_CONTENT { get; set; }
        public int ID_ORGANIZATION { get; set; }
        public int ID_CONTENT { get; set; }
        public int ID_USER { get; set; }
        public Nullable<int> CHOICE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE_TIME { get; set; }
    }
}
