//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sul_slot_seminar
    {
        public int slot_id { get; set; }
        public string slot { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<int> id_seminar { get; set; }
        public string speaker_name { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> update_date_time { get; set; }
    }
}
