//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_organisation_banner_links
    {
        public int id_organisation_banner_links { get; set; }
        public Nullable<int> id_organisation_banner { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> user_option { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
    }
}
