//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_data
    {
        public int ID_USER_DATA { get; set; }
        public int ID_USER { get; set; }
        public int ID_DEVICE_TYPE { get; set; }
        public string DEVICE_ID { get; set; }
        public int ID_ACTION { get; set; }
        public System.DateTime UPDATEDDATETIME { get; set; }
    
        public virtual tbl_action tbl_action { get; set; }
        public virtual tbl_device_type tbl_device_type { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
