//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_game_path
    {
        public int id_game_path { get; set; }
        public Nullable<int> id_category_tile { get; set; }
        public Nullable<int> id_category_heading { get; set; }
        public Nullable<int> id_category { get; set; }
        public Nullable<int> id_program { get; set; }
        public Nullable<int> Program_sequence_order { get; set; }
        public string is_program_mandatory { get; set; }
        public string program_weightage { get; set; }
        public string program_select_flag { get; set; }
        public Nullable<int> id_assessment { get; set; }
        public Nullable<int> assessment_sequence_order { get; set; }
        public string is_assessment_mandatory { get; set; }
        public Nullable<int> assessment_weightage { get; set; }
        public string assessment_select_flag { get; set; }
        public int id_game { get; set; }
    }
}
