//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_saksham_assessment_detail
    {
        public int id_saksham_assessment_detail { get; set; }
        public Nullable<int> id_saksham_assessment_master { get; set; }
        public Nullable<int> id_milestone { get; set; }
        public string milestone_description { get; set; }
        public Nullable<int> id_skill { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public string comments { get; set; }
    }
}
