//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_content_link
    {
        public int ID_CONTENT_LINK { get; set; }
        public int ID_CONTENT_PARENT { get; set; }
        public int ID_CONTENT_CHILD { get; set; }
        public string STATUS { get; set; }
        public System.DateTime UPDATED_DATE_TIME { get; set; }
        public int ID_LINK_TYPE { get; set; }
    }
}
