//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace m2ostnext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_game_assignment
    {
        public int id_game_assignment { get; set; }
        public Nullable<int> id_org { get; set; }
        public Nullable<int> id_game { get; set; }
        public Nullable<int> id_user { get; set; }
        public string status { get; set; }
        public string updated_datetime { get; set; }
    }
}
